-- 기존 데이터가 없을 때만 삽입
-- TextGuide.md에서 자동 생성됨 (npm run generate:data)

MERGE INTO memory (id, date, place, title, description, image_path, sort_order) KEY(id) VALUES
(1, '', '', '', '', '["/images/memory-001.jpg","/images/memory-002.jpg","/images/memory-003.jpg","/images/memory-004.jpg","/images/memory-005.jpg","/images/memory-006.jpg","/images/memory-007.jpg","/images/memory-008.jpg","/images/memory-009.jpg","/images/memory-010.jpg","/images/memory-011.jpg","/images/memory-012.jpg","/images/memory-013.jpg","/images/memory-014.jpg","/images/memory-015.jpg","/images/memory-016.jpg","/images/memory-017.jpg","/images/memory-018.jpg","/images/memory-019.jpg","/images/memory-020.jpg","/images/memory-021.jpg","/images/memory-022.jpg","/images/memory-023.jpg","/images/memory-024.jpg","/images/memory-025.jpg","/images/memory-026.jpg","/images/memory-027.jpg","/images/memory-028.jpg","/images/memory-029.jpg","/images/memory-030.jpg","/images/memory-031.jpg","/images/memory-032.jpg","/images/memory-033.jpg","/images/memory-034.jpg","/images/memory-035.jpg","/images/memory-036.jpg","/images/memory-037.jpg","/images/memory-038.jpg","/images/memory-039.jpg","/images/memory-040.jpg","/images/memory-041.jpg","/images/memory-042.jpg","/images/memory-043.jpg","/images/memory-044.jpg","/images/memory-045.jpg","/images/memory-046.jpg","/images/memory-047.jpg","/images/memory-048.jpg","/images/memory-049.jpg","/images/memory-050.jpg","/images/memory-051.jpg","/images/memory-052.jpg","/images/memory-053.jpg","/images/memory-054.jpg","/images/memory-055.jpg","/images/memory-056.jpg","/images/memory-057.jpg","/images/memory-058.jpg","/images/memory-059.jpg","/images/memory-060.jpg","/images/memory-061.jpg","/images/memory-062.jpg","/images/memory-063.jpg","/images/memory-064.jpg","/images/memory-065.jpg","/images/memory-066.jpg","/images/memory-067.jpg","/images/memory-068.jpg","/images/memory-069.jpg","/images/memory-070.jpg","/images/memory-071.jpg","/images/memory-072.jpg","/images/memory-073.jpg","/images/memory-074.jpg","/images/memory-075.jpg","/images/memory-076.jpg","/images/memory-077.jpg","/images/memory-078.jpg","/images/memory-079.jpg","/images/memory-080.jpg","/images/memory-081.jpg","/images/memory-082.jpg","/images/memory-083.jpg","/images/memory-084.jpg","/images/memory-085.jpg","/images/memory-086.jpg","/images/memory-087.jpg"]', 1)
;

MERGE INTO letter (id, greeting, closing, paragraphs) KEY(id) VALUES
(1,
 '사랑하는 당신에게',
 '영원히 사랑하는, 당신의 사람으로부터',
 '["우리가 함께한 모든 순간들이 떠올라. 처음 만났던 그 날부터 지금 이 순간까지, 매일이 선물 같았어.","네가 웃을 때마다 세상이 환해지는 것 같고, 네가 내 곁에 있다는 것만으로도 하루가 완벽해져.","앞으로도 우리의 이야기를 함께 써 나가고 싶어. 슬플 때도, 기쁠 때도, 평범한 날에도 항상 네 옆에 있고 싶어.","그래서 오늘, 용기를 내어 물어보려 해."]');